# Generated by Django 3.1.2 on 2020-10-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название района')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название темы')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('sex', models.CharField(choices=[('Муж', 'Муж'), ('Жен', 'Жен')], max_length=3, verbose_name='Пол')),
                ('age', models.CharField(choices=[('18 - 35', '18 - 35'), ('36 - 50', '36 - 50'), ('51 - 65', '51 - 65'), ('старше 65', 'старше 65')], max_length=10, verbose_name='Возраст')),
                ('district', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='consultations_on_district', to='consultation.district', verbose_name='Район')),
                ('status', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='consultations_on_status', to='consultation.status', verbose_name='Статус')),
                ('theme', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='consultations_on_theme', to='consultation.theme', verbose_name='Тема')),
            ],
        ),
    ]
