# Generated by Django 3.1.2 on 2020-10-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultation_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Темы', 'verbose_name_plural': 'Темы'},
        ),
    ]
