# Generated by Django 3.1.3 on 2020-11-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_auto_20201113_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название региона')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Консультации на карте',
                'verbose_name_plural': 'Консультации на карте',
            },
        ),
    ]
