# Generated by Django 3.1.3 on 2020-11-24 08:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_maptag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=755, verbose_name='Заголовок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка карты')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Центр консультаций',
                'verbose_name_plural': 'Центры консультаций',
            },
        ),
    ]
