# Generated by Django 3.1.3 on 2020-11-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_consultationcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationcenter',
            name='skype',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='skype'),
        ),
    ]
