# Generated by Django 3.1.2 on 2020-10-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос пользователя', 'verbose_name_plural': 'Вопросы пользователей'},
        ),
    ]
