# Generated by Django 3.1.2 on 2020-10-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20201009_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=1500, verbose_name='Вопрос'),
        ),
    ]
