# Generated by Django 3.1.2 on 2020-10-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20201026_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Часто задаваемый вопрос'),
        ),
    ]
