# Generated by Django 3.1.3 on 2020-11-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_faq_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=10, verbose_name='Буква')),
                ('description', models.CharField(max_length=455, verbose_name='Фраза к букве')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
