# Generated by Django 3.1.3 on 2020-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка')),
                ('url', models.URLField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Полезную ссылку',
                'verbose_name_plural': 'Полезные ссылки',
            },
        ),
    ]
