# Generated by Django 3.1.2 on 2020-10-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0003_auto_20201026_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
