# Generated by Django 3.1.2 on 2020-11-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article_tags', to='alphabet.Tag', verbose_name='Тэги (в том числе и для поисковых систем)'),
        ),
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('words', models.TextField(verbose_name='Ключевые слова')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='alphabet.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
