# Generated by Django 3.1.2 on 2020-11-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0005_auto_20201102_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatags',
            options={'verbose_name': 'Мета тэги для поисковых систем', 'verbose_name_plural': 'Мета тэги для поисковых систем'},
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='alphabet.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Картинку для слайдера',
                'verbose_name_plural': 'Картинки для слайдера',
            },
        ),
    ]
