# Generated by Django 3.1.2 on 2020-11-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0006_auto_20201102_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='alphabet.article', verbose_name='Статья'),
        ),
    ]
