# Generated by Django 3.1.3 on 2020-11-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0007_auto_20201102_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
