# Generated by Django 3.1.3 on 2020-11-17 07:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0008_auto_20201106_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Вставьте видео сюда'),
        ),
    ]
