# Generated by Django 3.1.3 on 2020-11-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0009_auto_20201117_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Шаг для рекомендаций статей',
                'verbose_name_plural': 'Шаги для рекомендаций статей',
            },
        ),
        migrations.CreateModel(
            name='StepTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alphabet.step', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Тег для шагов рекомендаций',
                'verbose_name_plural': 'Теги для шагов рекомендаций',
            },
        ),
    ]
