# Generated by Django 3.1.3 on 2020-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0010_step_steptag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='step_tags',
            field=models.ManyToManyField(related_name='article_step_tags', to='alphabet.StepTag', verbose_name="Тэги для раздела 'шаги рекоменаций'"),
        ),
    ]
