# Generated by Django 3.1.4 on 2020-12-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0012_auto_20201124_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер шага'),
        ),
    ]
