# Generated by Django 3.1.2 on 2020-10-05 14:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.CharField(max_length=355, verbose_name='Краткая аннотация')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PartOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workshop.day', verbose_name='День')),
            ],
            options={
                'verbose_name': 'Часть дня',
                'verbose_name_plural': 'Части дня',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Вопрос')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос - Ответ',
                'verbose_name_plural': 'Вопрос - Ответ',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Мастерская')),
            ],
            options={
                'verbose_name': 'Мастерскую',
                'verbose_name_plural': 'Мастерские',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
                ('part_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='workshop.partofday', verbose_name='Часть дня')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ссылка')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodologies', to='workshop.day', verbose_name='день')),
            ],
            options={
                'verbose_name': 'Методику',
                'verbose_name_plural': 'Методики',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('part_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshop.partofday', verbose_name='Часть дня')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ссылка')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='workshop.day', verbose_name='день')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workshop.workshop', verbose_name='мастерская'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ссылка')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='workshop.day', verbose_name='день')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
