# Generated by Django 3.1.2 on 2020-10-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
