# Generated by Django 3.1.2 on 2020-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20201008_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Лайк/дизлайк'),
        ),
    ]
