# Generated by Django 3.1.2 on 2020-10-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_like_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionModel',
        ),
    ]
