# Generated by Django 3.1.2 on 2020-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_delete_questionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='methodology',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='methodology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
