# Generated by Django 3.1.2 on 2020-10-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20201027_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='challenge_quantity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество челленджей'),
        ),
        migrations.AddField(
            model_name='day',
            name='lifehack_quantity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество лайфхаков'),
        ),
        migrations.AddField(
            model_name='day',
            name='video_quantity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество видео'),
        ),
    ]
