# Generated by Django 3.1.2 on 2020-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_auto_20201027_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-number'], 'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AddField(
            model_name='day',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер дня'),
        ),
    ]
