# Generated by Django 3.1.2 on 2020-11-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_auto_20201030_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355, verbose_name='Информация об мастерской')),
            ],
            options={
                'verbose_name': 'Информация об мастерской',
                'verbose_name_plural': 'Информация об мастерской',
            },
        ),
    ]
