# Generated by Django 3.1.3 on 2020-11-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='workshop.day', verbose_name='день'),
        ),
        migrations.AlterField(
            model_name='film',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films', to='workshop.day', verbose_name='день'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methodologies', to='workshop.day', verbose_name='день'),
        ),
    ]
