# Generated by Django 3.1.3 on 2020-11-17 02:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_auto_20201116_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Вставьте видео сюда'),
        ),
    ]
