# Generated by Django 3.1.3 on 2020-11-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_auto_20201116_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать день'),
        ),
        migrations.AddField(
            model_name='day',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отложенной публикации'),
        ),
    ]
