# Generated by Django 3.1.3 on 2020-11-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_auto_20201117_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BooleanField(default=False, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'tasks',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
