# Generated by Django 3.1.3 on 2020-11-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_auto_20201117_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='ссылка'),
        ),
    ]
