# Generated by Django 3.1.3 on 2020-11-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_testtasks'),
        ('workshop', '0015_auto_20201123_0828'),
    ]

    operations = [
    ]
