# Generated by Django 3.1.4 on 2020-12-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_merge_20201130_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTasks',
        ),
    ]
